type StatesT = string[];
type CitiesT = { c: string; s: number }[];

export const STATES: StatesT = [
	'Greater Poland',
	'Kujawsko-Pomorskie',
	'Lesser Poland Voivodeship',
	'Lodz Voivodeship',
	'Lower Silesia',
	'Lublin',
	'Lubusz',
	'Mazovia',
	'Opole Voivodeship',
	'Podlasie',
	'Pomerania',
	'Silesia',
	'Subcarpathian Voivodeship',
	'Swietokrzyskie',
	'Warmia-Masuria',
	'West Pomerania',
];
export const CITIES: CitiesT = [
	{ c: 'Borówiec', s: 0 },
	{ c: 'Kalisz', s: 0 },
	{ c: 'Konin', s: 0 },
	{ c: 'Koszalin', s: 0 },
	{ c: 'Mosina', s: 0 },
	{ c: 'Piła', s: 0 },
	{ c: 'Pleszew', s: 0 },
	{ c: 'Poznań', s: 0 },
	{ c: 'Szamotuły', s: 0 },
	{ c: 'Bydgoszcz', s: 1 },
	{ c: 'Fordon', s: 1 },
	{ c: 'Nakło nad Notecią', s: 1 },
	{ c: 'Solec Kujawski', s: 1 },
	{ c: 'Toruń', s: 1 },
	{ c: 'Włocławek', s: 1 },
	{ c: 'Kraków', s: 2 },
	{ c: 'Kurdwanów', s: 2 },
	{ c: 'Myślenice', s: 2 },
	{ c: 'Niepołomice', s: 2 },
	{ c: 'Olkusz', s: 2 },
	{ c: 'Rabka-Zdrój', s: 2 },
	{ c: 'Sucha Beskidzka', s: 2 },
	{ c: 'Szczawnica', s: 2 },
	{ c: 'Wadowice', s: 2 },
	{ c: 'Zabierzów', s: 2 },
	{ c: 'Zaborze', s: 2 },
	{ c: 'Ksawerów', s: 3 },
	{ c: 'Kutno', s: 3 },
	{ c: 'Łask', s: 3 },
	{ c: 'Łódź', s: 3 },
	{ c: 'Pabianice', s: 3 },
	{ c: 'Piotrków Trybunalski', s: 3 },
	{ c: 'Radomsko', s: 3 },
	{ c: 'Zgierz', s: 3 },
	{ c: 'Działoszyn', s: 4 },
	{ c: 'Dzierzoniów', s: 4 },
	{ c: 'Jedlina-Zdrój', s: 4 },
	{ c: 'Jelenia Góra', s: 4 },
	{ c: 'Kłodzko', s: 4 },
	{ c: 'Legnica', s: 4 },
	{ c: 'Lwówek Śląski', s: 4 },
	{ c: 'Nowa Ruda', s: 4 },
	{ c: 'Świebodzice', s: 4 },
	{ c: 'Wrocław', s: 4 },
	{ c: 'Biała Podlaska', s: 5 },
	{ c: 'Chełm', s: 5 },
	{ c: 'Janów Lubelski', s: 5 },
	{ c: 'Lublin', s: 5 },
	{ c: 'Radzyń Podlaski', s: 5 },
	{ c: 'Zamość', s: 5 },
	{ c: 'Nowa Sól', s: 6 },
	{ c: 'Olbrachcice', s: 6 },
	{ c: 'Sieniawa Zarska', s: 6 },
	{ c: 'Zagan', s: 6 },
	{ c: 'Zielona Góra', s: 6 },
	{ c: 'Ciemniewo', s: 7 },
	{ c: 'Konstancin-Jeziorna', s: 7 },
	{ c: 'Legionowo', s: 7 },
	{ c: 'Otwock', s: 7 },
	{ c: 'Piastów', s: 7 },
	{ c: 'Płock', s: 7 },
	{ c: 'Radom', s: 7 },
	{ c: 'Siedlce', s: 7 },
	{ c: 'Sierpc', s: 7 },
	{ c: 'Ursus', s: 7 },
	{ c: 'Warszawa', s: 7 },
	{ c: 'Wawer', s: 7 },
	{ c: 'Żyrardów', s: 7 },
	{ c: 'Brzeg', s: 8 },
	{ c: 'Głubczyce', s: 8 },
	{ c: 'Kędzierzyn-Koźle', s: 8 },
	{ c: 'Krapkowice', s: 8 },
	{ c: 'Krzanowice', s: 8 },
	{ c: 'Nysa', s: 8 },
	{ c: 'Olesno', s: 8 },
	{ c: 'Zdzieszowice', s: 8 },
	{ c: 'Augustów', s: 9 },
	{ c: 'Białystok', s: 9 },
	{ c: 'Grajewo', s: 9 },
	{ c: 'Łomża', s: 9 },
	{ c: 'Nowa Świdziałowka', s: 9 },
	{ c: 'Suwałki', s: 9 },
	{ c: 'Chojnice', s: 10 },
	{ c: 'Czarnówko', s: 10 },
	{ c: 'Gdańsk', s: 10 },
	{ c: 'Gdynia', s: 10 },
	{ c: 'Kościerzyna', s: 10 },
	{ c: 'Sopot', s: 10 },
	{ c: 'Ustka', s: 10 },
	{ c: 'Goczałkowice Zdrój', s: 11 },
	{ c: 'Międzybrodzie Żywieckie', s: 11 },
	{ c: 'Orzesze', s: 11 },
	{ c: 'Racibórz', s: 11 },
	{ c: 'Rybnik', s: 11 },
	{ c: 'Sosnowiec', s: 11 },
	{ c: 'Tychy', s: 11 },
	{ c: 'Zawiercie', s: 11 },
	{ c: 'Dębica', s: 12 },
	{ c: 'Jarosław', s: 12 },
	{ c: 'Krempna', s: 12 },
	{ c: 'Krosno', s: 12 },
	{ c: 'Nisko', s: 12 },
	{ c: 'Przemyśl', s: 12 },
	{ c: 'Rudnik nad Sanem', s: 12 },
	{ c: 'Rymanów-Zdrój', s: 12 },
	{ c: 'Rzeszów', s: 12 },
	{ c: 'Sanok', s: 12 },
	{ c: 'Tarnobrzeg', s: 12 },
	{ c: 'Kazimierz Wielki', s: 13 },
	{ c: 'Kępie', s: 13 },
	{ c: 'Kielce', s: 13 },
	{ c: 'Kije', s: 13 },
	{ c: 'Nowy Staw', s: 13 },
	{ c: 'Pinczów', s: 13 },
	{ c: 'Starachowice', s: 13 },
	{ c: 'Ełk', s: 14 },
	{ c: 'Gołdap', s: 14 },
	{ c: 'Olsztyn', s: 14 },
	{ c: 'Ostróda', s: 14 },
	{ c: 'Szczytno', s: 14 },
	{ c: 'Kamień Pomorski', s: 15 },
	{ c: 'Szczecin', s: 15 },
	{ c: 'Szczecinek', s: 15 },
];

export const INFO = [
	{
		index: 'Dobra (0-50)',
		color: '#abcf65',
		info: 'Jakość powietrza jest zadowalająca i stanowi niewielkie zagrożenie dla zdrowia lub nie stanowi go wcale. Zaleca się wietrzenie domu. Spędzaj czas na świeżym powietrzu. Zaleca się otwarcie okien i przewietrzenie domu, aby doprowadzić świeże, bogate w tlen powietrze.',
	},
	{
		index: 'Umiarkowana (51-100)',
		color: '#f5d55a',
		info: 'Jakość powietrza jest akceptowalna i stanowi niewielkie zagrożenie dla zdrowia. Osoby starsze i wrażliwe powinny unikać aktywności na świeżym powietrzu, ponieważ mogą odczuwać dolegliwości ze strony układu oddechowego. Osoby starsze i wrażliwe powinny również znacznie ograniczyć wysiłek fizyczny na świeżym powietrzu. Odradza się wietrzenie, a okna powinny być zamknięte.',
	},
	{
		index: 'Niekorzystna dla grup wrażliwych (101-150)',
		color: '#b83039',
		info: 'Ogół społeczeństwa, a w szczególności osoby starsze i wrażliwe, są narażone na ryzyko wystąpienia podrażnień i problemów z oddychaniem. Zaleca się ograniczenie wysiłku fizycznego na świeżym powietrzu. Osoby starsze i wrażliwe powinny unikać wszelkiej aktywności na świeżym powietrzu, a na zewnątrz powinny nosić maski chroniące przed zanieczyszczeniami. Odradza się wietrzenie pomieszczeń. Jeśli jakość powietrza w pomieszczeniach jest niezdrowa, należy włączyć oczyszczacze powietrza.',
	},
	{
		index: 'Zła (151-200)',
		color: '#f66768',
		info: 'Zwiększone prawdopodobieństwo niekorzystnych skutków i pogorszenia stanu serca i płuc wśród ogółu społeczeństwa - szczególnie w grupach osób starszych i wrażliwych. Wszyscy powinni unikać wysiłku fizycznego na świeżym powietrzu i nosić maski chroniące przed zanieczyszczeniami. Odradza się wietrzenie pomieszczeń. Oczyszczacze powietrza powinny być włączone.',
	},
	{
		index: 'Bardzo zła (201-300)',
		color: '#a47eba',
		info: 'Wpływ na ogół społeczeństwa będzie zauważalny. Osoby starsze i wrażliwe będą odczuwały zmniejszoną wytrzymałość podczas wykonywania czynności. Osoby te powinny pozostać w pomieszczeniach zamkniętych i ograniczyć aktywność. Wszyscy powinni unikać ćwiczeń na świeżym powietrzu, a na zewnątrz nosić maski przeciwpyłowe. Odradza się wietrzenie pomieszczeń. Oczyszczacze powietrza powinny być włączone.',
	},

	{
		index: 'Niebezpieczna (301-500)',
		color: '#a07785',
		info: 'Ogół społeczeństwa i grupy wrażliwe są w grupie wysokiego ryzyka wystąpienia silnych podrażnień i niekorzystnych skutków zdrowotnych, które mogą wywołać inne choroby. Wszyscy powinni unikać wysiłku fizycznego i pozostać w pomieszczeniach zamkniętych. Wszyscy powinni unikać wysiłku fizycznego na świeżym powietrzu i zadbać o noszenie maski przeciwpyłowej na zewnątrz. Odradza się wietrzenie pomieszczeń. Oczyszczacze powietrza powinny być włączone.',
	},
];
